### ISSUE TITLE
Automatic runscript dependency detection

### ISSUE THREAD

**Issue by codyd51** [gparmer/composite#212]
Hi,

If every component interface defines its dependencies in its makefile, why do users need to redefine the dependency graph when calling `llboot`? Could dependencies be parsed and loaded automatically without the need for explicitly stating them in the run script?

**Comment by gedare** [comment]
One question that comes to mind is whether a run script can specify a different implementation of the same interface to two different components. E.g. `a->b` and `c->b` (using `->` as "depends on") is what we expect when `b` implements an interface `a` and `c` both use, but is it permitted to have `a->b` and `c->d` where `b` and `d` implement the same interface? That would make it hard to infer the correct dependency when just given a list of components. I don't know if this is actually allowed or not.

**Comment by gparmer** [comment]
@codyd51 Great question as this is pretty non-intuitive.

@gedare hit on one aspect of this.  Dependencies are on *interfaces*, but to execute a system, we need a specific *implementation* of the interface (i.e. we need to make an actual binding for the polymorphism).  The runscripts do that by specifying *which* of the implementations of an interface to use.

Note also that different implementations will have different dependencies, so *which* implementation of an interface you chose can drastically change the shape of the component graph is.

**Comment by codyd51** [comment]
Interesting. Thanks for the info!
